heat_template_version: 2015-04-30

description:
  Isolates LB instance resource group

parameters:
  prefix:
    type: string
    description: String to make the name of all created resources unique
  cbam:
    type: json
  resources:
    type: json
    description: The data for this group
  rg_index:
    type: string
    description: Current index of the resource group ( ex. 0, 2)
    default: invalid
  loadBalancerMangementNet:
    type: string
    description: Management network for LoadBalancer
  loadBalancerFabricNet:
    type: string
    description: Control Switch Fabric network for LoadBalancer
  loadBalancerAllowedAddressPairList:
    type: comma_delimited_list
    description: Allowed IP address pair list for LoadBalancer External networks
  loadBalancerAntiAffinityGrp:
    type: string
    description: Anti Affinity group for LoadBalancer
  mtuSize:
    type: string
    description: MTU Size for Switch Fabric

resources:
  loadBalancerInstanceGroup:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: [ resources, { get_param: rg_index }, present ] }
      resource_def:
        type: cMG_LB.template.yaml
        properties:
          cbam: { get_param: cbam }
          prefix: { get_param: prefix }
          resources: { get_param: resources }
          loadBalancerMangementNet: { get_param: loadBalancerMangementNet }
          loadBalancerFabricNet: { get_param: loadBalancerFabricNet }
          rg_index: { get_param: rg_index }
          loadBalancerAllowedAddressPairList: { get_param: loadBalancerAllowedAddressPairList }
          loadBalancerAntiAffinityGrp: { get_param: loadBalancerAntiAffinityGrp }
          mtuSize: { get_param: mtuSize }
