heat_template_version: 2015-04-30

description:
  Isolates OAM as a complete resource together with associated ports

parameters:

  cbam:
    type: json
  resources:
    type: json
  prefix:
    type: string
    description: String to make the name of all created resources unique
  oamMgmtIp:
    type: string
    description: OAM IP address
  oamAllowedAddressPairs:
    type: comma_delimited_list
    description: OAM Allowed Address Pairs
  oamSlotId:
    type: string
    description: OAM Slot Id
  oamControlFabricNet:
    type: string
    description: Control Switch Fabric Network for OAM
  oamSystemIp:
    type: string
    description: OAM System IP address
  oamAntiAffinityGrp:
    type: string
    description: OAM Anti Affinity Group
  oamDisk1:
    type: string
    description: OAM CompactFlash1 Volume Id
  oamDisk2:
    type: string
    description: OAM CompactFlash2 Volume Id
  oamControlSwitchFabricIp:
    type: string
    description: OAM Control Switch Fabric IP
  mtuSize:
    type: string
    description: MTU Size for Switch Fabric
  oamMetadataIp:
    type: string
    description: OAM Management IP for Metadata

resources:
 oamManagementPort:
    type: OS::Neutron::Port
    properties:
      network: { get_param: [ cbam, externalConnectionPoints, oamManagementECP, networkId ] }
      security_groups: [ { get_param: [ cbam, extensions, securityGroup ] } ]
      replacement_policy: AUTO
      fixed_ips: [{
         "ip_address": { get_param: oamMgmtIp }
         }]
      allowed_address_pairs:
        repeat:
          for_each:
            <%ipaddr%>: { get_param: oamAllowedAddressPairs }
          template:
            ip_address: <%ipaddr%>

 oamControlSwitchFabricPort:
    type: OS::Neutron::Port
    properties:
      network: { get_param: oamControlFabricNet }
      replacement_policy: AUTO
      security_groups: [ { get_param: [ cbam, extensions, securityGroup ] } ]
      fixed_ips: [{
         "ip_address": { get_param: oamControlSwitchFabricIp }
         }]
      value_specs:
        # extra_dhcp_opts names are vendor specific. For Nuage opt_name=”mtu” should be used instead of “interface-mtu”
        extra_dhcp_opts:
        - {opt_name: interface-mtu, opt_value: { get_param: mtuSize }}

 oamServerInstance:
    type: OS::Nova::Server
    depends_on: [ oamManagementPort, oamControlSwitchFabricPort ]
    metadata: { "nokia_vnf_slotId": { get_param: oamSlotId }, "nokia_vnf_cardType":"OAM", "nokia_vnf_ipaddr": { get_param: oamMetadataIp }, "nokia_vnf_sysAddr": { get_param: oamSystemIp }, "nokia_vnf_scaleAspectInfo": "loadBalancerAspect:LB,mgRedundantAspect:MG", "nokia_vnf_smbios": { get_param: [ resources, smbios ] }, "nokia_vnf_csfIp": { get_param: [ resources, controlSwitchFabricIp ] } }
    properties:
      image_update_policy: "REPLACE"
      name: { list_join: [ "-", [ { get_param: prefix }, OAM, { get_param: oamSlotId } ] ] }
      image: { get_param: [ resources, imageId ] }
      flavor: { get_param: [ resources, flavorId ] }
      config_drive: "true"
      user_data:
        str_replace:
          template: "$oamSmbios"
          params:
            $oamSmbios: { get_param: [ resources, smbios ] }
      user_data_format: "RAW"
      networks:
        - port: { get_resource: oamManagementPort }
        - port: { get_resource: oamControlSwitchFabricPort }
      block_device_mapping_v2: [ { boot_index: "-1", volume_id: { get_param: oamDisk1 }, device_name: "vdb" }, { boot_index: "-1", volume_id: { get_param: oamDisk2 }, device_name: "vdc" } ]
      availability_zone: { get_param: [ resources, azId ] }
      scheduler_hints:
        group: { get_param: oamAntiAffinityGrp }
